# Generated by Django 4.1.3 on 2025-03-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrooveSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('description', models.CharField(max_length=500)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='GroovetimeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('profile_picture', models.URLField()),
                ('bio', models.CharField(max_length=500)),
                ('groove_points', models.FloatField()),
                ('grooves_won', models.PositiveIntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGroove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('start_day', models.CharField(max_length=40)),
                ('end_day', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GrooveSubmissionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groove_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.groovesubmission')),
                ('rating_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.rating')),
                ('user_submitted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.groovetimeuser')),
            ],
        ),
        migrations.CreateModel(
            name='grooveSubmissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=400)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('groove_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.groovesubmission')),
            ],
        ),
        migrations.AddField(
            model_name='groovesubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.groovetimeuser'),
        ),
        migrations.AddField(
            model_name='groovesubmission',
            name='user_ratings',
            field=models.ManyToManyField(to='groovetimeapi.rating'),
        ),
        migrations.AddField(
            model_name='groovesubmission',
            name='weekly_groove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.weeklygroove'),
        ),
    ]
