# Generated by Django 4.2.19 on 2025-03-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groove_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=250)),
                ('bio', models.CharField(max_length=200)),
                ('groove_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grooves_won', models.IntegerField()),
                ('date_joined', models.CharField(max_length=25)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_Groove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('start_day', models.CharField(max_length=25)),
                ('end_day', models.CharField(max_length=25)),
                ('submissions', models.ManyToManyField(blank=True, related_name='submissions_for_weekly_groove', to='groovetimeapi.groove_submission')),
            ],
        ),
        migrations.CreateModel(
            name='GrooveSubmissionComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_created', models.CharField(max_length=25)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.user_profile')),
                ('groove_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groove_submission_comments', to='groovetimeapi.groove_submission')),
            ],
        ),
        migrations.CreateModel(
            name='Groove_Submission_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groove_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_being_rated', to='groovetimeapi.groove_submission')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.user_profile')),
            ],
        ),
        migrations.AddField(
            model_name='groove_submission',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments_for_groove_submission', to='groovetimeapi.groovesubmissioncomments'),
        ),
        migrations.AddField(
            model_name='groove_submission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.user_profile'),
        ),
        migrations.AddField(
            model_name='groove_submission',
            name='user_ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings_for_groove_submission', to='groovetimeapi.groove_submission_rating'),
        ),
        migrations.AddField(
            model_name='groove_submission',
            name='weekly_groove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_weekly_groove', to='groovetimeapi.weekly_groove'),
        ),
    ]
