# Generated by Django 4.1.3 on 2025-03-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groovetimeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groovesubmissioncomment',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groovetimeapi.groovetimeuser'),
        ),
    ]
