# Generated by Django 4.2.17 on 2025-03-04 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groovetimeapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groove_submission',
            name='user_ratings',
        ),
        migrations.RemoveField(
            model_name='weekly_groove',
            name='submissions',
        ),
        migrations.AddField(
            model_name='groove_submission',
            name='user_ratings',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rating_submissions', to='groovetimeapi.groove_submission_rating'),
        ),
        migrations.AddField(
            model_name='weekly_groove',
            name='submissions',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_for_weekly_groove', to='groovetimeapi.groove_submission'),
            preserve_default=False,
        ),
    ]
