# Generated by Django 4.2.19 on 2025-03-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groovetimeapi', '0002_groovesubmissioncomment_commented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groovesubmission',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='groovesubmission',
            name='user_ratings',
            field=models.ManyToManyField(null=True, to='groovetimeapi.rating'),
        ),
    ]
