# Generated by Django 4.1.3 on 2025-03-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groovetimeapi', '0003_alter_groovesubmission_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groovesubmission',
            name='user_ratings',
            field=models.ManyToManyField(to='groovetimeapi.rating'),
        ),
        migrations.AlterField(
            model_name='groovetimeuser',
            name='groove_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='groovetimeuser',
            name='grooves_won',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
